### ISSUE TITLE
1.0.0 is not compatible with GEOSwift version 5.2

### ISSUE THREAD

**Issue by borut-t** [GEOSwift/GEOSwiftMapKit#5] opened 2019-10-23 08:42 UTC
```
s.dependency 'GEOSwift', '5.0.0'
```
Dependency is set to version `5.0.0` ☝️ , but `5.2.0` is already released. Can you update it?

**Comment by macdrevx** [comment] 2019-10-23 11:51
Yep, will do. Duplicate of #3

**Comment by borut-t** [comment] 2019-10-23 14:19
What’s the ETA on release?

**Comment by macdrevx** [comment] 2019-10-23 14:53
I can take care of it this week.

**Closed as completed** 2019-10-25 18:57 UTC
Labels: duplicate

**Comment by macdrevx** [comment] 2019-10-25 19:07
@borut-t I just released 1.1.0 and it fixes this issue. Let me know if it works for you.

**Comment by borut-t** [comment] 2019-10-25 20:01
@macdrevx it works. Thanks for quick action.
